# Generated by Django 5.0.12 on 2025-03-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_task_due_date_remove_task_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='description',
        ),
    ]
