# Generated by Django 5.0.12 on 2025-03-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_task_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
