# Generated by Django 5.0.12 on 2025-03-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_settingsaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsaccount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
