# Generated by Django 5.0.12 on 2025-03-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_settingsaccount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsaccount',
            name='interest_rates',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='settingsaccount',
            name='rental',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settingsaccount',
            name='utilities',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
