# Generated by Django 5.0.12 on 2025-03-15 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_settingsaccount_interest_rates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsaccount',
            old_name='so_id',
            new_name='id',
        ),
        migrations.CreateModel(
            name='DebtAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
    ]
