# Generated by Django 5.0.12 on 2025-03-17 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_debtaccount_amount_debtaccount_interest_rates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('reward_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('reward_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reward_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
