# Generated by Django 5.0.12 on 2025-03-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
