# Generated by Django 5.0.12 on 2025-03-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rewards_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsaccount',
            name='penalty_rates',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='score',
            field=models.IntegerField(default=100),
        ),
    ]
