# Generated by Django 5.0.12 on 2025-03-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_settingsaccount_penalty_rates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtaccount',
            name='penalty_rates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
