# Generated by Django 5.0.12 on 2025-03-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_debtaccount_penalty_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsaccount',
            name='seconds',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
